### ISSUE TITLE
Index exceeds matrix dimensions. 

### ISSUE THREAD

**Issue by jodyngo** [Mirsadeghi/BSIFT#1]
Please advise below error on BSIFT_demo.m:

Loading image and Homography transform files
Index exceeds matrix dimensions.
Error in BSIFT_demo (line 152)
    dpca(i,:) = (100*Num_PCA{i}(2,:)./Num_PCA{i}(1,:));

**Comment by Mirsadeghi** [comment]
Hi @jodyngo 
Apologize for the late response.
this error has occurred because all data not uploaded.
I have uploaded all the necessary data.
